FROM openjdk:17
EXPOSE 8080
ADD pet-clinic-data/target/petclinic-data.jar petclinic-data.jar
ENTRYPOINT ["java", "-jar", "petclinic-data.jar"]
#ADD pet-clinic-web/target/petclinic-web.jar petclinic-web.jar
#ENTRYPOINT ["java", "-jar", "petclinic-web.jar"]

#FROM openjdk:17
#EXPOSE 8080
#ADD pet-clinic-web/target/petclinic-web.jar petclinic-web.jar
#ENTRYPOINT ["java", "-jar", "petclinic-web.jar"]