#Standard Maven CICD Workflow
#Maintain different workflow for different modules
name: PetClinic-Data-Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml


  publish-job:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: mvn --batch-mode --update-snapshots verify
        #Be careful with the path for the target folder, this is for multi module
        # For non multi module project the target folder will be present at root
      - run: mkdir staging && cp pet-clinic-data/target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
            
      #workflow for building and pushing docker image to docker hub
      - name: Build & push Docker PetClinic-Data image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: astacode/petclinic-data
            tags: latest
            registry: docker.io
            dockerfile: Dockerfile-PetClinicData
            #set the secrets in github secrets
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}